### ISSUE TITLE
Should this be a public repo?

### ISSUE THREAD

**Issue by kevlarr** [LaunchAcademy/dyson_sphere#42]

**Comment by dpickett** [comment]
@kevlarr what's up man! Long time no talk. Yeah it's just our CSS / styleguide really. Nothing proprietary in here.

**Comment by kevlarr** [comment]
Cool! Just saw it so wanted to make sure

**Comment by kevlarr** [comment]
Not much is up here! Enjoying the new(ish) job still and hunkering down while the world somewhat ends. You know, same ol' same ol'.
